// DO NOT set the `name` and `ticker` properties manually
// Instead use one of the get token metadata scripts https://github.com/ExodusMovement/exodus-core/tree/master/packages/assets-base#get-token-metadata

export default [
  {
    name: '6p6x_solana_056c2704',
    displayName: 'TRUMP',
    decimals: 6,
    ticker: '6P6Xsolana056C2704',
    displayTicker: 'TRUMP',
    mintAddress: '6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN',
    info: {
      description:
        'TRUMP tokens are now live on the blockchain. On July 13, 2024, President Trump faced death and rose with strength and courage, rallying the world with his iconic battle cry FIGHT FIGHT FIGHT. This moment ignited a movement and became the meme of the century.',
      twitter: 'https://twitter.com/GetTrumpMemes',
      website: 'https://gettrumpmemes.com/',
    },
    primaryColor: '#CBB16D',
    gradientColors: ['#AF8B4F', '#E9D68C'],
  },
  {
    name: 'fuaf_solana_2f933a22',
    displayName: 'Official Melania Meme',
    decimals: 6,
    ticker: 'FUAFsolana2F933A22',
    displayTicker: 'MELANIA',
    mintAddress: 'FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P',
    info: {
      description:
        'Melania memes are digital collectibles designed to express support for and engage with the values symbolized by MELANIA.',
      twitter: 'https://twitter.com/MELANIATRUMP',
      website: 'https://melaniameme.com/',
    },
    primaryColor: '#FFFFFF',
    gradientColors: ['#DEDEDE', '#FFFFFF'],
  },
  {
    name: '7dhb_solana_c9e04412',
    displayName: 'Lido Staked SOL',
    decimals: 9,
    ticker: '7DHBsolanaC9E04412',
    displayTicker: 'stSOL',
    mintAddress: '7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj',
    info: {
      description:
        'When someone stakes their SOL with Lido, they instantly receive stSOL tokens in return. The stSOL tokens increase in value over time and can be used in other DeFi products while the SOL is staked.',
      telegram: 'https://t.me/lidofinance',
      reddit: 'https://reddit.com/r/lidofinance',
      twitter: 'https://twitter.com/lidofinance',
      website: 'https://www.lido.fi',
    },
    primaryColor: '#00A3FF',
    gradientColors: ['#00A3FF', '#3ADCFF'],
  },
  {
    name: '7i5k_solana_c9e04412',
    displayName: 'STEPN',
    decimals: 9,
    ticker: '7I5KsolanaC9E04412',
    displayTicker: 'GMT',
    mintAddress: '7i5KKsX2weiTkry7jA4ZwSuXGhs5eJBEjY8vVxR4pfRx',
    info: {
      description:
        'The Green Metaverse Token is used for governance in STEPN, a gamified health app that rewards users for physical movement such as jogging outside.',
      reddit: 'https://www.reddit.com/r/StepN/',
      twitter: 'https://twitter.com/Stepnofficial',
      website: 'https://www.stepn.com/',
      telegram: 'https://t.me/STEPNannouncement',
    },
    primaryColor: '#E6BC7B',
    gradientColors: ['#FFE5C0', '#E6BC7B'],
  },
  {
    name: 'audius_solana',
    displayName: 'Audius',
    decimals: 8,
    ticker: 'AUDIOSOL',
    displayTicker: 'AUDIO',
    mintAddress: '9LzCMqDgTKYz9Drzqnpgee3SGa89up3a247ypMj2xrqM',
    primaryColor: '#ED43FF',
    gradientColors: ['#EAEAEA', '#FFF'],
  },
  {
    name: 'eche_solana_c5cba5c4',
    displayName: 'Bonfida',
    decimals: 6,
    ticker: 'ECHEsolanaC5CBA5C4',
    displayTicker: 'FIDA',
    mintAddress: 'EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp',
    info: {
      description:
        'FIDA is a Solana-based governance token that offers multiple services such as a graphical user interface for the Serum DEX and Solana data analytics.',
      website: 'https://bonfida.org/#/',
      telegram: 'https://t.me/bonfidatg',
    },
    primaryColor: '#6868FC',
    gradientColors: ['#A0A0FF', '#6868FC'],
  },
  {
    name: '7atg_solana_3506aeb0',
    displayName: 'Catwifhat',
    decimals: 2,
    ticker: '7ATGsolana3506AEB0',
    displayTicker: 'CWIF',
    mintAddress: '7atgF8KQo4wJrD5ATGX7t1V2zVvykPJbFfNeVf1icFv1',
    info: {
      description: 'Catwifhat is a deflationary memecoin on the Solana network.',
      website: 'https://www.catwifhatsolana.com/',
    },
    primaryColor: '#DBDBDB',
    gradientColors: ['#FFFFFF', '#DBDBDB'],
  },
  {
    name: 'dezx_solana_3b523050',
    displayName: 'Bonk',
    decimals: 5,
    ticker: 'DEZXsolana3B523050',
    displayTicker: 'BONK',
    mintAddress: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
    info: {
      description: 'BONK is a memecoin that gave users airdrops of BONK on the Solana network.',
      website: 'https://www.bonkcoin.com/',
    },
    primaryColor: '#6868FC',
    gradientColors: ['#A0A0FF', '#6868FC'],
  },
  {
    name: 'jupy_solana_ed7ebe51',
    displayName: 'Jupiter',
    decimals: 6,
    ticker: 'JUPYsolanaED7EBE51',
    displayTicker: 'JUP',
    mintAddress: 'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',
    info: {
      description:
        'JUP is the governance token of the Jupiter platform, originally split 50% to the community and 50% to the Jupiter ecosystem team.  Holders are expecting to vote on token mints and initiatives within the Jupiter platform.',
      twitter: 'https://twitter.com/JupiterExchange',
      website: 'https://jup.ag/',
    },
    primaryColor: '#00FFC8',
    gradientColors: ['#98C158', '#C7F284'],
  },
  {
    name: 'mefn_solana_5d11b887',
    displayName: 'Magic Eden',
    decimals: 6,
    ticker: 'MEFNsolana5D11B887',
    displayTicker: 'ME',
    mintAddress: 'MEFNBXixkEbait3xn9bkm8WsJzXtVsaJEn4c8Sam21u',
    info: {
      description:
        'Magic Eden is the top consumer dApp in crypto for everyone. Their vision is to make digital ownership universal.',
      twitter: 'https://x.com/MEFndn',
      website: 'https://mefoundation.com/',
    },
    primaryColor: '#E42575',
    gradientColors: ['#E42575', '#FFC7C2'],
  },
  {
    name: 'msol_solana_c9e04412',
    displayName: 'Marinade Staked SOL',
    decimals: 9,
    ticker: 'MSOLsolanaC9E04412',
    displayTicker: 'mSOL',
    mintAddress: 'mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So',
    info: {
      description:
        'Marinade Staked SOL is a token users receive for staking their SOL with Marinade, the first liquid staking protocol built on Solana. While earning staking rewards with Marinade, users can earn even more by using their mSOL for borrowing, lending, and other DeFi use cases.',
      twitter: 'https://twitter.com/MarinadeFinance',
      website: 'https://marinade.finance/',
    },
    primaryColor: '#C8ECE1',
    gradientColors: ['#308DBA', '#C8ECE1'],
  },
  {
    name: 'orca_solana',
    displayName: 'Orca',
    decimals: 6,
    ticker: 'ORCASOL',
    displayTicker: 'ORCA',
    mintAddress: 'orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE',
    info: {
      description:
        'Orca is an AMM on Solana where users can exchange assets with low fees and get rewarded for providing liquidity to trading pools.',
      reddit: 'https://www.reddit.com/r/orca_so',
      twitter: 'https://twitter.com/orca_so',
      website: 'https://orca.so',
      telegram: 'https://t.me/orca_so',
    },
    primaryColor: '#5969DB',
    gradientColors: ['#1D257A', '#5969DB'],
  },
  {
    name: 'poli_solana_0cc3745c',
    displayName: 'Star Atlas DAO',
    decimals: 8,
    ticker: 'POLIsolana0CC3745C',
    displayTicker: 'POLIS',
    mintAddress: 'poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk',
    info: {
      description:
        'Star Atlas DAO (POLIS) is the governance token for Star Atlas, an expansive, breathtaking gaming metaverse. POLIS holders can participate in decisions that affect how Star Atlas is operated.',
      reddit: 'https://reddit.com/r/staratlas',
      twitter: 'https://twitter.com/staratlas',
      website: 'https://staratlas.com',
    },
    primaryColor: '#32FFFF',
    gradientColors: ['#32FFFF', '#EDFEFF'],
  },
  {
    name: '2b1k_solana_f3924eb0',
    displayName: 'PayPal USD',
    decimals: 6,
    ticker: '2B1KsolanaF3924EB0',
    displayTicker: 'PYUSD',
    mintAddress: '2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo',
    info: {
      description: 'A stablecoin pegged to the US Dollar, issued by PayPal.',
      website: 'https://www.paypal.com/pyusd',
    },
    primaryColor: '#0071F3',
    gradientColors: ['#0071F3', '#338EF8'],
  },
  {
    name: 'raydium',
    displayName: 'Raydium',
    decimals: 6,
    ticker: 'RAY',
    mintAddress: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
    info: {
      description:
        'Raydium, an AMM (Automated Market Market), powers DeFi on the Solana blockchain, providing on-chain liquidity for the Serum Decentralized Exchange. This means lightning fast token swaps and a whole lot more!',
      twitter: 'https://twitter.com/RaydiumProtocol',
      website: 'https://raydium.io/',
      telegram: 'https://t.me/raydiumprotocol',
    },
    primaryColor: '#3772FF',
    gradientColors: ['#3772FF', '#C200FB'],
  },
  {
    name: 'serum',
    displayName: 'Serum',
    decimals: 6,
    ticker: 'SRM',
    mintAddress: 'SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt',
    info: {
      description:
        'SRM tokens power Serum, a centralized exchange software system built on the Solana blockchain. It allows for trading of cryptocurrencies and has the advantage of a cross-chain support, meaning that it enables a trustless exchange of crypto between various blockchains.',
      reddit: 'https://www.reddit.com/r/ProjectSerum/',
      twitter: 'https://twitter.com/ProjectSerum',
      website: 'https://projectserum.com/',
    },
    primaryColor: '#71E0EC',
    gradientColors: ['#71E0EC', '#05AAC5'],
  },
  {
    name: 'smoothlovepotion_solana',
    displayName: 'Smooth Love Potion',
    decimals: 8,
    ticker: 'SLPSOL',
    displayTicker: 'SLP',
    mintAddress: '4hpngEp1v3CXpeKB81Gw4sv7YvwUVRKvY3SGag9ND8Q4',
    primaryColor: '#77BAA1',
    gradientColors: ['#EAEAEA', '#FFF'],
  },
  {
    name: 'staratlas_solana',
    displayName: 'Star Atlas',
    decimals: 8,
    ticker: 'ATLASSOL',
    displayTicker: 'ATLAS',
    mintAddress: 'ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx',
    info: {
      description:
        'Star Atlas is a massive multiplayer online game in a breathtaking metaverse run on Solana. Players can travel in space, build space stations, form alliances, and battle for virtual assets.',
      reddit: 'https://reddit.com/r/staratlas',
      twitter: 'https://twitter.com/staratlas',
      website: 'https://staratlas.com',
      telegram: 'https://t.me/staratlasgame',
    },
    primaryColor: '#32FFFF',
    gradientColors: ['#32FFFF', '#EDFEFF'],
  },
  {
    name: 'tetherusd_solana',
    displayName: 'Tether USD',
    decimals: 6,
    ticker: 'USDTSOL',
    displayTicker: 'USDT',
    mintAddress: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
    primaryColor: '#53AE94',
    gradientColors: ['#EAEAEA', '#FFF'],
  },
  {
    name: 'thegraph_solana',
    displayName: 'The Graph',
    decimals: 8,
    ticker: 'GRTSOL',
    displayTicker: 'GRT',
    mintAddress: 'HGsLG4PnZ28L8A4R5nPqKgZd86zUUdmfnkTRnuFJ5dAX',
    primaryColor: '#33A0FF',
    gradientColors: ['#EAEAEA', '#FFF'],
  },
  {
    name: 'usdcoin_solana',
    displayName: 'USDC',
    decimals: 6,
    ticker: 'USDCSOL',
    displayTicker: 'USDC',
    mintAddress: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    primaryColor: '#3E90E8',
    gradientColors: ['#EAEAEA', '#FFF'],
  },
]
