import { keyBy } from '@exodus/basic-utils'

import assetsList from '../index.js'

const assets = keyBy(assetsList, 'name')

const tokens = Object.values(assets).filter(
  (asset) => asset.baseAssetName === 'ethereum' && asset.name !== 'ethereum'
)

const tokenNames = tokens.map((t) => t.name)

// Assets are sorted multiple times. We are removing the requirement to have them sorted in libraries.

test('assert we are not missing anyone', () => {
  // A bit of duplicated data, but validates that between commit we are not updating or removing the wrong token.
  expect(tokenNames.sort()).toEqual(
    [
      'aave',
      'ach_ethereum_fbad19a6',
      'aeron',
      'agix_ethereum_84616c96',
      'aion',
      'airswap',
      'alchemix',
      'ali_ethereum_9ae8d1eb',
      'amp',
      'ankr',
      'ape',
      'api3',
      'aragon',
      'aragonv2',
      'audius',
      'augur',
      'augurv2',
      'axieinfinity',
      'balancer',
      'bancor',
      'band_ethereum_a9ddc2a2',
      'bat',
      'binance',
      'bit_ethereum_9656e191',
      'blur_ethereum_ef097961',
      'bnktothefuture',
      'bone_ethereum_1cdd7eb5',
      'busd',
      'cbeth_ethereum_32621dca',
      'cdai',
      'ceek_ethereum_63dd5f1b',
      'chainlink',
      'chiliz',
      'civic',
      'compound',
      'coti',
      'cro',
      'crv',
      'cvx',
      'decentraland',
      'dent',
      'dentacoin',
      'digix',
      'dydx',
      'enjincoin',
      'ens',
      'fantom',
      'fet_ethereum_6609900b',
      'forth_ethereum_52c00d9e',
      'fox',
      'frax',
      'frax_share',
      'funfair',
      'gala_ethereum_3e0e1736',
      'geminidollar',
      'gnosis',
      'golem',
      'golemv2',
      'holo',
      'huobi',
      'icon',
      'iexec',
      'illuvium',
      'imx',
      'jasmy_ethereum_2c1e076b',
      'kyberv2',
      'leash_ethereum_562b149d',
      'leo',
      'lidodao',
      'livepeer',
      'looks_ethereum_222f7656',
      'loomv2',
      'loopring',
      'lqty_ethereum_126a91b0',
      'lyxe_ethereum_00e25dfc',
      'maker',
      'mask_ethereum_c2890c79',
      'mcd',
      'mdt_ethereum_1bb644a2',
      'metal',
      'metis_ethereum_54dc1156',
      'mithril',
      'mxc_ethereum_c4923be4',
      'nexo_ethereum_fe4d2476',
      'numeraire',
      'ocean_ethereum_1abd4fcf',
      'ogn_ethereum_fcc7cc39',
      'olympusv2',
      'omisego',
      'oneinch',
      'ousd_ethereum_48fcf72d',
      'paxgold',
      'paxos',
      'pepe_ethereum_22ed551c',
      'perp_ethereum_c75f71b4',
      'pillar',
      'polygon',
      'pol_ethereum_e5c9fadc',
      'populous',
      'powerledger',
      'pyusd_ethereum_871d3761',
      'qtum',
      'quant',
      'quantstamp',
      'radar_ethereum_e4d48030',
      'rarible',
      'ren',
      'render',
      'request',
      'reth_ethereum_40b16905',
      'revain',
      'revainnew',
      'ripio',
      'rlb_ethereum_a7e53179',
      'rpl_ethereum_2f6fb917',
      'rsr_ethereum_a5eb8f84',
      'salt',
      'sandbox',
      'sdao_ethereum_c59ee345',
      'shibainu',
      'smoothlovepotion',
      'snx',
      'sportx',
      'status',
      'steth',
      'storj',
      'storm',
      'stormx',
      'sushiswap',
      'syn_ethereum_c7f5e6b8',
      'tel_ethereum_02bc2dbb',
      'tenx',
      'tetherusd',
      'thegraph',
      'trb_ethereum_ad699fe9',
      'tru_ethereum_922b250a',
      'trueusd',
      'uma',
      'uniswap',
      'usdcoin',
      'verasity',
      'viberate',
      'voyager',
      'wax',
      'wbtc',
      'weth',
      'wnxm_ethereum_52ead9a6',
      'woo_ethereum_0b749579',
      'yfi',
      'ygg',
      'zerox',
    ].sort()
  )
})

test('tokens have a description', () => {
  // console.log(
  //   tokens
  //     .filter((token) => !token.info.description)
  //     .map((name) => `'${name}'`)
  //     .join(',')
  // )
  const tokensWithoutDescription = new Set([
    'aave',
    'adtoken',
    'aion',
    'cdai',
    'dent',
    'dragon',
    'eos',
    'icon',
    'kin',
    'medishares',
    'pillar',
    'qash',
    'qtum',
    'rivetz',
    'santiment',
    'sushiswap',
    'taas',
    'timenewbank',
    'tron',
    'leo',
    'veritaseum',
    'walton',
  ])
  expect(
    tokens
      .filter((token) => !tokensWithoutDescription.has(token.name))
      .every((token) => token.info.description)
  ).toBe(true)
})
